### ISSUE TITLE
Margin at home's project card location icon

### ISSUE THREAD

**Issue by bernardocs** [catarse/catarse#2748]
Hey!

I noticed that the location icon and the location text are really close together.
![image](https://user-images.githubusercontent.com/513789/29187311-9c1ed7da-7de5-11e7-9d3d-60afc089032d.png)

I went inside the project page to see if there the location would also be like that and, as a matter of fact, it is not:
![image](https://user-images.githubusercontent.com/513789/29187458-33107d42-7de6-11e7-91b2-fc9a043e5916.png)

I had some trouble upon building the project on my work's machine... so as soon as I arrive home I'll try to submit a PR. It'll probably a little addition to a `_main.scss`:
```scss
// It'll be good to add a class to this icon... but let's stick to the `.fa-map-marker`
.card-project-author .fa.fa-map-marker {
  margin-right: 0.25em;
}
```

Using devtools and manually styling it, the result would be something like that:
![image](https://user-images.githubusercontent.com/513789/29187781-6998b1bc-7de7-11e7-9b11-3a052d02e1a4.png)

I'll create a PR as soon as I get to build the app at home and test it properly.

:parrot:
